spring:
  redis:
    host: 124.222.204.211
    port: 6379
    database: 1                # redis16库中的哪一库，默认0
    client-name: redis
    password: 123456
    timeout: 3000              # 连接超时时间（毫秒）
    jedis.pool.max-active: 8   #redis的连接池最大连接数
    jedis.pool.max-idle: 8     #redis的连接池中最大连接空闲数
    jedis.pool.max-wait: -1    #redis的连接池中最大等待时间，-1，表示没有限制
    jedis.pool.min-idle: 0     #redis的连接池中最小连接空闲数
  web:
    resources:
      static-locations: classpath:/static/, classpath:/templates/
  thymeleaf:
    prefix: classpath:/templates  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix: .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5
  datasource:
    druid:
    username: root
    password: 123456
    url: jdbc:mysql://124.222.204.211:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j,config
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa: #JPA配置
    hibernate:
      ddl-auto: none   #数据库有表就更新，无表就创建
    show-sql: true     #显示sql语句


